package info.denisjtorresg.wsproxy.bcn;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Tipo de Cambio - Banco Central de Nicaragua
 *
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-21T09:33:00.856-06:00
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "Tipo_Cambio_BCN", 
                  wsdlLocation = "ServicioTC.wsdl",
                  targetNamespace = "http://servicios.bcn.gob.ni/") 
public class TipoCambioBCN extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicios.bcn.gob.ni/", "Tipo_Cambio_BCN");
    public final static QName TipoCambioBCNSoap = new QName("http://servicios.bcn.gob.ni/", "Tipo_Cambio_BCNSoap");
    public final static QName TipoCambioBCNSoap12 = new QName("http://servicios.bcn.gob.ni/", "Tipo_Cambio_BCNSoap12");
    static {
        URL url = TipoCambioBCN.class.getResource("ServicioTC.wsdl");
        if (url == null) {
            url = TipoCambioBCN.class.getClassLoader().getResource("ServicioTC.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(TipoCambioBCN.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "ServicioTC.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public TipoCambioBCN(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TipoCambioBCN(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TipoCambioBCN() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns TipoCambioBCNSoap
     */
    @WebEndpoint(name = "Tipo_Cambio_BCNSoap")
    public TipoCambioBCNSoap getTipoCambioBCNSoap() {
        return super.getPort(TipoCambioBCNSoap, TipoCambioBCNSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TipoCambioBCNSoap
     */
    @WebEndpoint(name = "Tipo_Cambio_BCNSoap")
    public TipoCambioBCNSoap getTipoCambioBCNSoap(WebServiceFeature... features) {
        return super.getPort(TipoCambioBCNSoap, TipoCambioBCNSoap.class, features);
    }
    /**
     *
     * @return
     *     returns TipoCambioBCNSoap
     */
    @WebEndpoint(name = "Tipo_Cambio_BCNSoap12")
    public TipoCambioBCNSoap getTipoCambioBCNSoap12() {
        return super.getPort(TipoCambioBCNSoap12, TipoCambioBCNSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TipoCambioBCNSoap
     */
    @WebEndpoint(name = "Tipo_Cambio_BCNSoap12")
    public TipoCambioBCNSoap getTipoCambioBCNSoap12(WebServiceFeature... features) {
        return super.getPort(TipoCambioBCNSoap12, TipoCambioBCNSoap.class, features);
    }

}
