package info.denisjtorresg.wsproxy.bcn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-21T09:33:00.849-06:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://servicios.bcn.gob.ni/", name = "Tipo_Cambio_BCNSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TipoCambioBCNSoap {

    /**
     * Recupera el detalle completo de la base de tipos de cambio para el mes solicitado.
     * Parametros: (Año, Mes)
     */
    @WebResult(name = "RecuperaTC_MesResult", targetNamespace = "http://servicios.bcn.gob.ni/")
    @RequestWrapper(localName = "RecuperaTC_Mes", targetNamespace = "http://servicios.bcn.gob.ni/", className = "info.denisjtorresg.ws.cliente.bcn.RecuperaTCMes")
    @WebMethod(operationName = "RecuperaTC_Mes", action = "http://servicios.bcn.gob.ni/RecuperaTC_Mes")
    @ResponseWrapper(localName = "RecuperaTC_MesResponse", targetNamespace = "http://servicios.bcn.gob.ni/", className = "info.denisjtorresg.ws.cliente.bcn.RecuperaTCMesResponse")
    public info.denisjtorresg.wsproxy.bcn.RecuperaTCMesResponse.RecuperaTCMesResult recuperaTCMes(
        @WebParam(name = "Ano", targetNamespace = "http://servicios.bcn.gob.ni/")
        int ano,
        @WebParam(name = "Mes", targetNamespace = "http://servicios.bcn.gob.ni/")
        int mes
    );

    /**
     * Recupera el tipo de cambio del día solicitado.
     * Parametros: (Año, Mes, Día)
     */
    @WebResult(name = "RecuperaTC_DiaResult", targetNamespace = "http://servicios.bcn.gob.ni/")
    @RequestWrapper(localName = "RecuperaTC_Dia", targetNamespace = "http://servicios.bcn.gob.ni/", className = "info.denisjtorresg.ws.cliente.bcn.RecuperaTCDia")
    @WebMethod(operationName = "RecuperaTC_Dia", action = "http://servicios.bcn.gob.ni/RecuperaTC_Dia")
    @ResponseWrapper(localName = "RecuperaTC_DiaResponse", targetNamespace = "http://servicios.bcn.gob.ni/", className = "info.denisjtorresg.ws.cliente.bcn.RecuperaTCDiaResponse")
    public double recuperaTCDia(
        @WebParam(name = "Ano", targetNamespace = "http://servicios.bcn.gob.ni/")
        int ano,
        @WebParam(name = "Mes", targetNamespace = "http://servicios.bcn.gob.ni/")
        int mes,
        @WebParam(name = "Dia", targetNamespace = "http://servicios.bcn.gob.ni/")
        int dia
    );
}
