package info.denisjtorresg.tcbcn;

import java.util.Date;
import java.util.Map;
import java.util.Map.Entry;

/**
*
* @author Denis.Torres
*/
public class JPrueba extends javax.swing.JFrame {

   /** Creates new form JPrueba */
   public JPrueba() {
       initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

       jScrollPane1 = new javax.swing.JScrollPane();
       jTextArea1 = new javax.swing.JTextArea();
       jPanel1 = new javax.swing.JPanel();
       jLabel1 = new javax.swing.JLabel();
       fInicio = new javax.swing.JFormattedTextField();
       jLabel2 = new javax.swing.JLabel();
       fFin = new javax.swing.JFormattedTextField();
       cmdBuscar = new javax.swing.JButton();
       jPanel2 = new javax.swing.JPanel();
       chkProcy = new javax.swing.JCheckBox();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jTextArea1.setColumns(20);
       jTextArea1.setRows(5);
       jScrollPane1.setViewportView(jTextArea1);

       getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

       jPanel1.setLayout(new java.awt.GridLayout(3, 2));

       jLabel1.setText("Inicio dd-mm-aaaa");
       jPanel1.add(jLabel1);

       fInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
       jPanel1.add(fInicio);

       jLabel2.setText("Fin dd-mm-aaaa");
       jPanel1.add(jLabel2);

       fFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
       jPanel1.add(fFin);

       cmdBuscar.setText("Buscar");
       cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               cmdBuscarActionPerformed(evt);
           }
       });
       jPanel1.add(cmdBuscar);

       getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

       jPanel2.setLayout(new java.awt.BorderLayout());

       chkProcy.setText("Estoy detrás de un proxy");
       jPanel2.add(chkProcy, java.awt.BorderLayout.CENTER);

       getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

       pack();
   }// </editor-fold>

   private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {
	   jTextArea1.setText("");
	   
	   if(chkProcy.isSelected()){
		   System.setProperty("java.net.useSystemProxies", "true");
		   //TipoCambioBCNSimple.reset();
	   }
	   
	   Double tcHoy = TipoCambioBCNSimple.getTipoCambio();
	   Map<Date, Double> tcRango = null;
	   Double tcDia = 0.0;
	   
	   if(fInicio.getText()!=null && fInicio.getText().length()>0 && fFin.getText()!=null && fFin.getText().length()>0){
		   tcRango = TipoCambioBCNSimple.getTipoCambio(fInicio.getText(), fFin.getText());
	   }
	   
	   if(fInicio.getText()!=null && fInicio.getText().length()>0){
		   tcDia = TipoCambioBCNSimple.getTipoCambio(fInicio.getText());
	   }
	   
	   String texto = "Tipo de Cambio Hoy: " + tcHoy + "\n";
	   texto += "Tipo de Cambio del día " + fInicio.getText() + " es " + tcDia + "\n";
	   
	   if(tcRango!=null){
		   for(Entry<Date, Double> elemento: tcRango.entrySet()){
				Date fecha = elemento.getKey();
				Double tc = elemento.getValue();
				
				texto += fecha + " => " + tc + "\n";
		   }
	   }
	   
	   jTextArea1.setText(texto);
	   
   }

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {

           public void run() {
               new JPrueba().setVisible(true);
           }
       });
   }
   // Variables declaration - do not modify
   private javax.swing.JCheckBox chkProcy;
   private javax.swing.JButton cmdBuscar;
   private javax.swing.JFormattedTextField fFin;
   private javax.swing.JFormattedTextField fInicio;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea jTextArea1;
   // End of variables declaration
}
